### ISSUE TITLE
Is it possible to search the entire reddit posts based on keywords?

### ISSUE THREAD

**Issue by Rqcker** [rly0nheart/reddit-post-scraping-tool#11]
When I try to use `rpst -k 'my keyword' -s 'all' -t all -j` 

I find that the use of the r/all parameter doesn't seem to be supported. And I'm not getting any useful data with `1.6.1.0`

![image](https://github.com/bellingcat/reddit-post-scraping-tool/assets/20661419/6c9c3064-832e-4a95-b6df-5d9e24359eb9)

I only got it; `Starting new HTTPS connection (1): ` so how can i use this tool...

If so, can I have an example of how to use it?

**Comment by rly0nheart** [comment]
Hello @Rqcker, so I ran it with the same arguments you specified, and this was the output;
![Screenshot_20230813_110753_Termux](https://github.com/bellingcat/reddit-post-scraping-tool/assets/74001397/e7e1c8d2-1205-437d-bdf7-41f33eedaaf9)

Then I took a look at the r/economy subreddit, and it doesnt seem like anyone mentions 'economy' in the post texts or title. So this is not an erro in the program, it's a user issue😅.

**Comment by rly0nheart** [comment]
> When I try to use `rpst -k 'my keyword' -s 'all' -t all -j`
> 
> I find that the use of the r/all parameter doesn't seem to be supported. And I'm not getting any useful data with `1.6.1.0`
> 
> ![image](https://user-images.githubusercontent.com/20661419/260236079-6c9c3064-832e-4a95-b6df-5d9e24359eb9.png)
> 
> I only got it; `Starting new HTTPS connection (1): ` so how can i use this tool...
> 
> If so, can I have an example of how to use it?

If you want to get a result from r/economy, try setting the limit of posts to 100 with the `-c/--limit` flag. Your command should look like this

`
rpst -k economy -s economy -c 100 -j
`
this will return exactly 1 post and save it to a json file. Like I said, no one seems to talk about the economy in the post text or title.

Let me know how it goes after running the command I just gave you.

> It seems, even if you pass the `-t all` option you will still get 1 post.

**Comment by Rqcker** [comment]
@rly0nheart Thanks for the answer. 

But if I want to get a keyword on the whole reddit. How do I use it? Instead of a single subreddit.

Can I use `-s all `?

**Comment by rly0nheart** [comment]
Hm no, it doesn't work like that. It only lets  you look for posts in a subreddit.
