### ISSUE TITLE
question: is this tool still working after reddit's changes?

### ISSUE THREAD

**Issue by msramalho** [rly0nheart/reddit-post-scraping-tool#2]
Reddit paywalled it's API, is this tool capable of working around that or should it be archived?

**Comment by rly0nheart** [comment]
> Reddit paywalled it's API, is this tool capable of working around that or should it be archived?

These are from the query I ran just now. It still works, maybe I just need to add some more features (If necessary).

![Screenshot_20230805_165930_Termux.jpg](https://github.com/bellingcat/reddit-post-scraping-tool/assets/74001397/26033b80-7a01-45f8-bf9f-31efc8b0dc07)

![Screenshot_20230805_165952_Termux.jpg](https://github.com/bellingcat/reddit-post-scraping-tool/assets/74001397/e75c154a-539b-4ba5-bbde-01c4730c2bbf)

![Screenshot_20230805_165959_Termux.jpg](https://github.com/bellingcat/reddit-post-scraping-tool/assets/74001397/df5ca88a-1478-4d70-8071-716d70718a30)
